### PR TITLE
Fixed namespace commands

### LINKED ISSUE #111: Namespace command is not working
1. Expected behavior and actual behavior.

``nem2-cli namespace info`` and ``nem2-cli namespace owned`` raises the following error:

```
Error TypeError: Cannot read property 'name' of undefined
    at namespace.levels.map.map (C:\Users\user\AppData\Roaming\npm\node_modules\nem2-cli\node_modules\nem2-sdk\dist\src\service\NamespaceService.js:47:51)
    at Array.map (<anonymous>)
    at NamespaceService.extractFullNamespace (C:\Users\user\AppData\Roaming\npm\node_modules\nem2-cli\node_modules\nem2-sdk\dist\src\service\NamespaceService.js:47:14)
    at MapSubscriber.namespaceHttp.getNamespacesName.pipe.operators_1.map [as project] (C:\Users\user\AppData\Roaming\npm\node_modules\nem2-cli\node_modules\nem2-sdk\dist\src\service\NamespaceService.js:37:181)
    at MapSubscriber._next (C:\Users\user\AppData\Roaming\npm\node_modules\nem2-cli\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (C:\Users\user\AppData\Roaming\npm\node_modules\nem2-cli\node_modules\rxjs\internal\Subscriber.js:66:18)
    at CatchSubscriber.Subscriber._next (C:\Users\user\AppData\Roaming\npm\node_modules\nem2-cli\node_modules\rxjs\internal\Subscriber.js:89:26)
    at CatchSubscriber.Subscriber.next (C:\Users\user\AppData\Roaming\npm\node_modules\nem2-cli\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MapSubscriber._next (C:\Users\user\AppData\Roaming\npm\node_modules\nem2-cli\node_modules\rxjs\internal\operators\map.js:55:26)
    at MapSubscriber.Subscriber.next (C:\Users\user\AppData\Roaming\npm\node_modules\nem2-cli\node_modules\rxjs\internal\Subscriber.js:66:18)

```

Probably caused by https://github.com/nemtech/catapult-rest/issues/128 or nem2-sdk.

2. Steps to reproduce the problem.

* ``nem2-cli namespace info --name cat.currency``
* ``nem2-cli namespace owned--address <address>``

3. Specifications like the version of the project, operating system, or hardware.

* nem2-cli@0.13.1
* nem2-sdk@0.13.3
* https://github.com/nemtech/catapult-rest/commit/2de71cacfbf31f7408d9d52fb796197bd4ce78dc

### PR DESCRIPTION
**Pull request by dgarcia360**
Closes #111

### CODE REVIEW

File: src/commands/namespace/info.ts [hunk 1]
```diff
@@ -41,34 +41,33 @@ export class CommandOptions extends ProfileOptions {
...
                     ['Alias Type', 'Address'],
-                    ['Alias Address', namespace.alias.address.pretty()],
+                    ['Alias Address', namespaceInfo.alias.address.pretty()],
                 );
-            } else if (namespace.alias.mosaicId) {
+            } else if (namespaceInfo.alias.mosaicId) {
                 this.table.push(
                     ['Alias Type', 'MosaicId'],
-                    ['Alias MosaicId', namespace.alias.mosaicId.toHex()],
+                    ['Alias MosaicId', namespaceInfo.alias.mosaicId.toString()],
```
Comment (rg911) [inline src/commands/namespace/info.ts]: this is going to fail in v0.14.0 now, as Alias.MosaicId is not instance of `MosaicId`. Should change back to toHex()

Comment (dgarcia360) [reply src/commands/namespace/info.ts]: Thanks! Will change it when updating to 0.14
